all:
  hosts:
    pod1:
      ansible_host: 192.168.49.2
      ansible_port: 30001
      ansible_user: ansible
    pod2:
      ansible_host: 192.168.49.2
      ansible_port: 30002
      ansible_user: ansible
